[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
transform = { workspace = true }
wgpu = { version = "25.0.2", features = ["fragile-send-sync-non-atomic-wasm"] }

[lints]
workspace = true
